### ISSUE TITLE
Graceful shutdown hangs if server process was killed or died.

### ISSUE THREAD

**Issue by Jaxkr** [WorldQL/mc_provisioner#4]
Expected behavior: The tmux session is stopped.
Actual behavior: provisioner waits forever for a tmux session with no process running
![image](https://user-images.githubusercontent.com/1147244/147814866-de7385b7-7959-43c6-8983-753cae7fc592.png)

To reproduce:
1. `./provisioner start`.
2. `tmux a -t mammoth_server_255xx`.
3. Kill the server with Control+C and press enter. Optionally, press the up arrow to select a previous command. Optionally hit enter a few tiles. This is bug is intermittent but only happens when NO process is running in the tmux window.
4. `./provisioner stop` will hang forever.

**Comment by luludotdev** [comment]
This was due to how graceful shutdown signalling was implemented. I've added a configurable wait timeout (defaults to 10s) that will just barrel ahead and forcibly stop the server if the timeout is hit.
