### ISSUE TITLE
Users can push specific files to a their servers without syncing all of them.

### ISSUE THREAD

**Issue by Jaxkr** [WorldQL/mc_provisioner#8]
![image](https://user-images.githubusercontent.com/1147244/148104228-2694b8e4-30be-49c8-ada7-bb2cb0521edf.png)

**Comment by Jaxkr** [comment]
Here's a potential solution that works well with your `sync_dirs` feature:
```
provisioner sync dir_name
```
This allows users to separate data into safe and unsafe to sync. For example, I would use this to push updates to the Mammoth jarfile by
1. Making a sync_dir called "plugins_to_sync" with a "plugins" folder inside it.
2. Placing the Mammoth jarfile and any config files for it inside `plugins_to_sync/plugins`.
3. `provisioner sync plugins_to_sync` would only copy files from `plugins_to_sync`.

Users often want to push a very limited subset of files to their servers when doing maintenence in production and I think this would be an easy-to-implement feature to facilitate that. Thoughts?

**Comment by luludotdev** [comment]
Right now this is already possible by overriding the list of dirs for a single command invocation.

```sh
$ ./provisioner --sync-dir plugins_to_sync sync
```

Albeit this isn't the best UX since the sync dir flag is global and comes before the sync command.

**Comment by Jaxkr** [comment]
good enough for me.
